sudo: required
services:
  - docker

before_install:
  - docker build -t saisarath151/docker-react -f Dockerfile.dev  .

script:
  - docker run -e CI=true saisarath151/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-953930874212"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
